name: Release User Deposit

on:
  issues:
    types: [ opened ]

jobs:
  get-user-address:
    name: Get User Address
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/get-user-address-action@v1
        id: user-address
        with:
          username: ${{ github.event.issue.user.login }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.user-address.outputs.address }}
      - run: echo ${{ github.event.issue.labels[0].name }}
